#ifndef PEPLUS_VERSION_HPP_
#define PEPLUS_VERSION_HPP_

#define PEPLUS_VERSION_STRING "@PEPlus_VERSION@"

#define PEPLUS_VERSION_MAJOR  @PEPlus_VERSION_MAJOR@
#define PEPLUS_VERSION_MINOR  @PEPlus_VERSION_MINOR@
#define PEPLUS_VERSION_PATCH  @PEPlus_VERSION_PATCH@

#endif